// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: transaction/transaction.proto

package transaction

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TransactionsClient is the client API for Transactions service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionsClient interface {
	// Simple rpc. client kirim dan menunggu response
	CreateTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Response, error)
	// Server Side Streaming. client kirim dan mendapatkan berbagai response sampai selesai. notice ada stream pada returns.
	ListTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (Transactions_ListTransactionClient, error)
}

type transactionsClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionsClient(cc grpc.ClientConnInterface) TransactionsClient {
	return &transactionsClient{cc}
}

func (c *transactionsClient) CreateTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/transaction.Transactions/CreateTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionsClient) ListTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (Transactions_ListTransactionClient, error) {
	stream, err := c.cc.NewStream(ctx, &Transactions_ServiceDesc.Streams[0], "/transaction.Transactions/ListTransaction", opts...)
	if err != nil {
		return nil, err
	}
	x := &transactionsListTransactionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Transactions_ListTransactionClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type transactionsListTransactionClient struct {
	grpc.ClientStream
}

func (x *transactionsListTransactionClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TransactionsServer is the server API for Transactions service.
// All implementations must embed UnimplementedTransactionsServer
// for forward compatibility
type TransactionsServer interface {
	// Simple rpc. client kirim dan menunggu response
	CreateTransaction(context.Context, *Transaction) (*Response, error)
	// Server Side Streaming. client kirim dan mendapatkan berbagai response sampai selesai. notice ada stream pada returns.
	ListTransaction(*Transaction, Transactions_ListTransactionServer) error
	mustEmbedUnimplementedTransactionsServer()
}

// UnimplementedTransactionsServer must be embedded to have forward compatible implementations.
type UnimplementedTransactionsServer struct {
}

func (UnimplementedTransactionsServer) CreateTransaction(context.Context, *Transaction) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTransaction not implemented")
}
func (UnimplementedTransactionsServer) ListTransaction(*Transaction, Transactions_ListTransactionServer) error {
	return status.Errorf(codes.Unimplemented, "method ListTransaction not implemented")
}
func (UnimplementedTransactionsServer) mustEmbedUnimplementedTransactionsServer() {}

// UnsafeTransactionsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionsServer will
// result in compilation errors.
type UnsafeTransactionsServer interface {
	mustEmbedUnimplementedTransactionsServer()
}

func RegisterTransactionsServer(s grpc.ServiceRegistrar, srv TransactionsServer) {
	s.RegisterService(&Transactions_ServiceDesc, srv)
}

func _Transactions_CreateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionsServer).CreateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transaction.Transactions/CreateTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionsServer).CreateTransaction(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transactions_ListTransaction_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Transaction)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TransactionsServer).ListTransaction(m, &transactionsListTransactionServer{stream})
}

type Transactions_ListTransactionServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type transactionsListTransactionServer struct {
	grpc.ServerStream
}

func (x *transactionsListTransactionServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

// Transactions_ServiceDesc is the grpc.ServiceDesc for Transactions service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Transactions_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transaction.Transactions",
	HandlerType: (*TransactionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTransaction",
			Handler:    _Transactions_CreateTransaction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListTransaction",
			Handler:       _Transactions_ListTransaction_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "transaction/transaction.proto",
}
